#!/usr/bin/env python3
"""Export current local JSON artifacts into idempotent Postgres seed SQL."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import uuid
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = ROOT / "output"
CONFIG_DIR = ROOT / "config"
DB_DIR = ROOT / "db"
DEFAULT_OUTPUT = DB_DIR / "seed_current_state.sql"
UUID_NAMESPACE = uuid.UUID("d54d4f84-a839-45b8-9001-e8daf127fdf2")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate SQL seed data from the project's current JSON outputs."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output SQL file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    sql = build_seed_sql()
    output_path = args.output if args.output.is_absolute() else (ROOT / args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql, encoding="utf-8")
    print(f"Wrote seed SQL: {output_path}")
    return 0


def build_seed_sql() -> str:
    tracked_markets = load_json(CONFIG_DIR / "tracked_markets.json")
    settlement_sources = load_json(CONFIG_DIR / "kalshi_settlement_sources.json")
    latest_markets = load_json(OUTPUT_DIR / "kalshi" / "latest_markets.json")
    noaa_weather = load_json(OUTPUT_DIR / "weather" / "latest_forecasts_noaa.json")
    open_meteo_weather = load_json(OUTPUT_DIR / "weather" / "latest_forecasts.json")
    scored_markets = load_json(OUTPUT_DIR / "models" / "latest_scored_markets.json")
    noaa_history = load_json(OUTPUT_DIR / "history" / "latest_noaa_history.json")
    bankroll_history = load_json(OUTPUT_DIR / "bets" / "bankroll" / "bankroll_history.json")

    bet_payloads = load_bet_payloads()

    tracked_by_market = {row["market_id"]: row for row in tracked_markets}
    tracked_by_series = {}
    for row in tracked_markets:
        for series in row.get("kalshi_series", []):
            tracked_by_series[series] = row

    lines: list[str] = []
    emit = lines.append
    emit("-- Generated by scripts/export_seed_sql.py")
    emit(f"-- Source workspace: {ROOT}")
    emit(f"-- Generated at: {dt.datetime.now(dt.timezone.utc).isoformat()}")
    emit("begin;")
    emit("set search_path to app, public;")
    emit("")

    emit_reference_seed(emit, tracked_markets, settlement_sources)
    emit_kalshi_seed(emit, latest_markets, tracked_by_series)
    emit_weather_seed(emit, noaa_weather, open_meteo_weather)
    emit_observation_seed(emit, noaa_history)
    emit_scored_seed(emit, scored_markets)
    emit_daily_bets_seed(emit, bet_payloads)
    emit_bankroll_seed(emit, bankroll_history)

    emit("commit;")
    emit("")
    return "\n".join(lines)


def emit_reference_seed(emit, tracked_markets: list[dict[str, Any]], settlement_sources: list[dict[str, Any]]) -> None:
    emit("-- market locations")
    for row in tracked_markets:
        emit(
            """
insert into app.market_locations (
  market_id, city, contract, event_type, latitude, longitude, timezone, kalshi_series, location_aliases
)
values (
  {market_id}, {city}, {contract}, {event_type}, {latitude}, {longitude}, {timezone}, {kalshi_series}, {location_aliases}
)
on conflict (market_id) do update
set city = excluded.city,
    contract = excluded.contract,
    event_type = excluded.event_type,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    timezone = excluded.timezone,
    kalshi_series = excluded.kalshi_series,
    location_aliases = excluded.location_aliases,
    updated_at = now();
""".strip().format(
                market_id=sql_value(row["market_id"]),
                city=sql_value(row["location"]),
                contract=sql_value(row["contract"]),
                event_type=sql_value(row["event_type"]),
                latitude=sql_value(row["latitude"]),
                longitude=sql_value(row["longitude"]),
                timezone=sql_value(row["timezone"]),
                kalshi_series=sql_array(row.get("kalshi_series", [])),
                location_aliases=sql_array(row.get("location_aliases", [])),
            )
        )
        emit("")

    emit("-- settlement source mappings")
    for row in settlement_sources:
        emit(
            """
insert into app.settlement_sources (
  series_ticker, market_id, city, kalshi_market_title, status, kalshi_source_label, kalshi_source_url,
  settlement_station_name, settlement_station_id, settlement_station_latitude, settlement_station_longitude,
  settlement_dataset, settlement_product, notes
)
values (
  {series_ticker}, {market_id}, {city}, {kalshi_market_title}, {status}, {kalshi_source_label}, {kalshi_source_url},
  {settlement_station_name}, {settlement_station_id}, {settlement_station_latitude}, {settlement_station_longitude},
  {settlement_dataset}, {settlement_product}, {notes}
)
on conflict (series_ticker) do update
set market_id = excluded.market_id,
    city = excluded.city,
    kalshi_market_title = excluded.kalshi_market_title,
    status = excluded.status,
    kalshi_source_label = excluded.kalshi_source_label,
    kalshi_source_url = excluded.kalshi_source_url,
    settlement_station_name = excluded.settlement_station_name,
    settlement_station_id = excluded.settlement_station_id,
    settlement_station_latitude = excluded.settlement_station_latitude,
    settlement_station_longitude = excluded.settlement_station_longitude,
    settlement_dataset = excluded.settlement_dataset,
    settlement_product = excluded.settlement_product,
    notes = excluded.notes,
    updated_at = now();
""".strip().format(
                series_ticker=sql_value(row["series_ticker"]),
                market_id=sql_value(row["market_id"]),
                city=sql_value(row["city"]),
                kalshi_market_title=sql_value(row["kalshi_market_title"]),
                status=sql_value(row.get("status")),
                kalshi_source_label=sql_value(row.get("kalshi_source_label")),
                kalshi_source_url=sql_value(row.get("kalshi_source_url")),
                settlement_station_name=sql_value(row.get("settlement_station_name")),
                settlement_station_id=sql_value(row.get("settlement_station_id")),
                settlement_station_latitude=sql_value(row.get("settlement_station_latitude")),
                settlement_station_longitude=sql_value(row.get("settlement_station_longitude")),
                settlement_dataset=sql_value(row.get("settlement_dataset")),
                settlement_product=sql_value(row.get("settlement_product")),
                notes=sql_value(row.get("notes")),
            )
        )
        emit("")


def emit_kalshi_seed(emit, latest_markets: dict[str, Any], tracked_by_series: dict[str, dict[str, Any]]) -> None:
    markets = latest_markets.get("markets", [])
    events: dict[str, dict[str, Any]] = {}

    emit("-- kalshi events and markets")
    for market in markets:
        event_ticker = market["event_ticker"]
        close_time = market.get("close_time")
        event_date = parse_event_date(event_ticker, market.get("title"), close_time)
        existing = events.get(event_ticker)
        if existing is None:
            events[event_ticker] = {
                "event_ticker": event_ticker,
                "series_ticker": market.get("series_ticker"),
                "series_title": market.get("series_title"),
                "series_slug": market.get("series_slug"),
                "event_date": event_date,
                "close_time": close_time,
                "open_time": market.get("open_time"),
                "status": market.get("status"),
            }
        elif existing["close_time"] is None and close_time is not None:
            existing["close_time"] = close_time

    for event in events.values():
        emit(
            """
insert into app.kalshi_events (
  event_ticker, series_ticker, series_title, series_slug, event_date, close_time, open_time, status
)
values (
  {event_ticker}, {series_ticker}, {series_title}, {series_slug}, {event_date}, {close_time}, {open_time}, {status}
)
on conflict (event_ticker) do update
set series_ticker = excluded.series_ticker,
    series_title = excluded.series_title,
    series_slug = excluded.series_slug,
    event_date = excluded.event_date,
    close_time = excluded.close_time,
    open_time = excluded.open_time,
    status = excluded.status,
    updated_at = now();
""".strip().format(
                event_ticker=sql_value(event["event_ticker"]),
                series_ticker=sql_value(event.get("series_ticker")),
                series_title=sql_value(event.get("series_title")),
                series_slug=sql_value(event.get("series_slug")),
                event_date=sql_value(event.get("event_date")),
                close_time=sql_value(event.get("close_time")),
                open_time=sql_value(event.get("open_time")),
                status=sql_value(event.get("status")),
            )
        )
        emit("")

    for market in markets:
        emit(
            """
insert into app.kalshi_markets (
  ticker, event_ticker, series_ticker, title, subtitle, market_type, strike_type,
  floor_strike, cap_strike, functional_strike, custom_strike, status, result
)
values (
  {ticker}, {event_ticker}, {series_ticker}, {title}, {subtitle}, {market_type}, {strike_type},
  {floor_strike}, {cap_strike}, {functional_strike}, {custom_strike}, {status}, {result}
)
on conflict (ticker) do update
set event_ticker = excluded.event_ticker,
    series_ticker = excluded.series_ticker,
    title = excluded.title,
    subtitle = excluded.subtitle,
    market_type = excluded.market_type,
    strike_type = excluded.strike_type,
    floor_strike = excluded.floor_strike,
    cap_strike = excluded.cap_strike,
    functional_strike = excluded.functional_strike,
    custom_strike = excluded.custom_strike,
    status = excluded.status,
    result = excluded.result,
    updated_at = now();
""".strip().format(
                ticker=sql_value(market["ticker"]),
                event_ticker=sql_value(market["event_ticker"]),
                series_ticker=sql_value(market.get("series_ticker")),
                title=sql_value(market.get("title")),
                subtitle=sql_value(market.get("subtitle")),
                market_type=sql_value(market.get("market_type")),
                strike_type=sql_value(market.get("strike_type")),
                floor_strike=sql_value(market.get("floor_strike")),
                cap_strike=sql_value(market.get("cap_strike")),
                functional_strike=sql_value(market.get("functional_strike")),
                custom_strike=sql_value(market.get("custom_strike")),
                status=sql_value(market.get("status")),
                result=sql_value(market.get("result")),
            )
        )
        emit("")

        snapshot_hash = hash_json(
            {
                "yes_bid_dollars": market.get("yes_bid_dollars"),
                "yes_ask_dollars": market.get("yes_ask_dollars"),
                "no_bid_dollars": market.get("no_bid_dollars"),
                "no_ask_dollars": market.get("no_ask_dollars"),
                "last_price_dollars": market.get("last_price_dollars"),
                "implied_probability": market.get("implied_probability"),
                "volume": market.get("volume"),
                "volume_24h": market.get("volume_24h"),
            }
        )
        emit(
            """
insert into app.kalshi_market_snapshots (
  id, pulled_at, ticker, event_ticker, yes_bid_dollars, yes_ask_dollars, no_bid_dollars, no_ask_dollars,
  last_price_dollars, implied_probability, volume, volume_24h, state_hash
)
values (
  {id}, {pulled_at}, {ticker}, {event_ticker}, {yes_bid_dollars}, {yes_ask_dollars}, {no_bid_dollars}, {no_ask_dollars},
  {last_price_dollars}, {implied_probability}, {volume}, {volume_24h}, {state_hash}
)
on conflict (ticker, pulled_at) do update
set event_ticker = excluded.event_ticker,
    yes_bid_dollars = excluded.yes_bid_dollars,
    yes_ask_dollars = excluded.yes_ask_dollars,
    no_bid_dollars = excluded.no_bid_dollars,
    no_ask_dollars = excluded.no_ask_dollars,
    last_price_dollars = excluded.last_price_dollars,
    implied_probability = excluded.implied_probability,
    volume = excluded.volume,
    volume_24h = excluded.volume_24h,
    state_hash = excluded.state_hash,
    inserted_at = now();
""".strip().format(
                id=sql_value(str(deterministic_uuid("kalshi_snapshot", market["ticker"], market.get("pulled_at")))),
                pulled_at=sql_value(market.get("pulled_at")),
                ticker=sql_value(market["ticker"]),
                event_ticker=sql_value(market["event_ticker"]),
                yes_bid_dollars=sql_value(market.get("yes_bid_dollars")),
                yes_ask_dollars=sql_value(market.get("yes_ask_dollars")),
                no_bid_dollars=sql_value(market.get("no_bid_dollars")),
                no_ask_dollars=sql_value(market.get("no_ask_dollars")),
                last_price_dollars=sql_value(market.get("last_price_dollars")),
                implied_probability=sql_value(market.get("implied_probability")),
                volume=sql_value(market.get("volume")),
                volume_24h=sql_value(market.get("volume_24h")),
                state_hash=sql_value(snapshot_hash),
            )
        )
        emit("")


def emit_weather_seed(emit, noaa_weather: list[dict[str, Any]], open_meteo_weather: list[dict[str, Any]]) -> None:
    emit("-- weather snapshots")
    for provider_payload in (noaa_weather, open_meteo_weather):
        for snapshot in provider_payload:
            provider = snapshot.get("provider")
            market = snapshot["market"]
            snapshot_id = str(
                deterministic_uuid(
                    "weather_snapshot",
                    provider,
                    market["market_id"],
                    snapshot.get("pulled_at"),
                )
            )
            provider_meta = {k: v for k, v in snapshot.items() if k not in {"provider", "pulled_at", "market", "current", "hourly", "daily", "units"}}
            state_hash = hash_json(
                {
                    "current": snapshot.get("current"),
                    "hourly": snapshot.get("hourly"),
                    "daily": snapshot.get("daily"),
                }
            )
            emit(
                """
insert into app.weather_snapshots (
  id, provider, pulled_at, market_id, location, latitude, longitude, timezone, current_json, units_json,
  provider_meta_json, state_hash
)
values (
  {id}, {provider}, {pulled_at}, {market_id}, {location}, {latitude}, {longitude}, {timezone},
  {current_json}, {units_json}, {provider_meta_json}, {state_hash}
)
on conflict (provider, market_id, pulled_at) do update
set location = excluded.location,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    timezone = excluded.timezone,
    current_json = excluded.current_json,
    units_json = excluded.units_json,
    provider_meta_json = excluded.provider_meta_json,
    state_hash = excluded.state_hash,
    inserted_at = now();
""".strip().format(
                    id=sql_value(snapshot_id),
                    provider=sql_value(provider),
                    pulled_at=sql_value(snapshot.get("pulled_at")),
                    market_id=sql_value(market["market_id"]),
                    location=sql_value(market["location"]),
                    latitude=sql_value(market["latitude"]),
                    longitude=sql_value(market["longitude"]),
                    timezone=sql_value(market["timezone"]),
                    current_json=sql_json(snapshot.get("current", {})),
                    units_json=sql_json(snapshot.get("units", {})),
                    provider_meta_json=sql_json(provider_meta),
                    state_hash=sql_value(state_hash),
                )
            )
            emit("")

            emit(f"delete from app.weather_hourly_forecasts where snapshot_id = {sql_value(snapshot_id)};")
            for hourly in snapshot.get("hourly", []):
                emit(
                    """
insert into app.weather_hourly_forecasts (
  snapshot_id, forecast_time, temperature_2m, dew_point_2m, relative_humidity_2m, pressure_msl,
  precipitation, cloud_cover, wind_speed_10m, wind_gusts_10m, probability_of_precipitation, short_forecast
)
values (
  {snapshot_id}, {forecast_time}, {temperature_2m}, {dew_point_2m}, {relative_humidity_2m}, {pressure_msl},
  {precipitation}, {cloud_cover}, {wind_speed_10m}, {wind_gusts_10m}, {probability_of_precipitation}, {short_forecast}
)
on conflict (snapshot_id, forecast_time) do update
set temperature_2m = excluded.temperature_2m,
    dew_point_2m = excluded.dew_point_2m,
    relative_humidity_2m = excluded.relative_humidity_2m,
    pressure_msl = excluded.pressure_msl,
    precipitation = excluded.precipitation,
    cloud_cover = excluded.cloud_cover,
    wind_speed_10m = excluded.wind_speed_10m,
    wind_gusts_10m = excluded.wind_gusts_10m,
    probability_of_precipitation = excluded.probability_of_precipitation,
    short_forecast = excluded.short_forecast;
""".strip().format(
                        snapshot_id=sql_value(snapshot_id),
                        forecast_time=sql_value(hourly.get("time")),
                        temperature_2m=sql_value(hourly.get("temperature_2m")),
                        dew_point_2m=sql_value(hourly.get("dew_point_2m")),
                        relative_humidity_2m=sql_value(hourly.get("relative_humidity_2m")),
                        pressure_msl=sql_value(hourly.get("pressure_msl")),
                        precipitation=sql_value(hourly.get("precipitation")),
                        cloud_cover=sql_value(hourly.get("cloud_cover")),
                        wind_speed_10m=sql_value(hourly.get("wind_speed_10m")),
                        wind_gusts_10m=sql_value(hourly.get("wind_gusts_10m")),
                        probability_of_precipitation=sql_value(hourly.get("probability_of_precipitation")),
                        short_forecast=sql_value(hourly.get("short_forecast")),
                    )
                )
            emit("")

            emit(f"delete from app.weather_daily_forecasts where snapshot_id = {sql_value(snapshot_id)};")
            for daily in snapshot.get("daily", []):
                emit(
                    """
insert into app.weather_daily_forecasts (
  snapshot_id, forecast_date, temperature_2m_max, temperature_2m_min, precipitation_sum,
  wind_speed_10m_max, wind_gusts_10m_max
)
values (
  {snapshot_id}, {forecast_date}, {temperature_2m_max}, {temperature_2m_min}, {precipitation_sum},
  {wind_speed_10m_max}, {wind_gusts_10m_max}
)
on conflict (snapshot_id, forecast_date) do update
set temperature_2m_max = excluded.temperature_2m_max,
    temperature_2m_min = excluded.temperature_2m_min,
    precipitation_sum = excluded.precipitation_sum,
    wind_speed_10m_max = excluded.wind_speed_10m_max,
    wind_gusts_10m_max = excluded.wind_gusts_10m_max;
""".strip().format(
                        snapshot_id=sql_value(snapshot_id),
                        forecast_date=sql_value(daily.get("date")),
                        temperature_2m_max=sql_value(daily.get("temperature_2m_max")),
                        temperature_2m_min=sql_value(daily.get("temperature_2m_min")),
                        precipitation_sum=sql_value(daily.get("precipitation_sum")),
                        wind_speed_10m_max=sql_value(daily.get("wind_speed_10m_max")),
                        wind_gusts_10m_max=sql_value(daily.get("wind_gusts_10m_max")),
                    )
                )
            emit("")


def emit_observation_seed(emit, noaa_history: dict[str, Any]) -> None:
    emit("-- historical observations")
    for location in noaa_history.get("locations", []):
        market = location.get("market", {})
        station = location.get("station", {})
        observations = location.get("observations", [])
        for observation in observations:
            row_id = str(
                deterministic_uuid(
                    "daily_observation",
                    market.get("market_id"),
                    observation.get("date"),
                    "ncei_ghcnd",
                )
            )
            emit(
                """
insert into app.daily_observations (
  id, market_id, observation_date, source_type, station_id, station_name, tmax_f, source_url, raw_text
)
values (
  {id}, {market_id}, {observation_date}, {source_type}, {station_id}, {station_name}, {tmax_f}, {source_url}, {raw_text}
)
on conflict (market_id, observation_date, source_type) do update
set station_id = excluded.station_id,
    station_name = excluded.station_name,
    tmax_f = excluded.tmax_f,
    source_url = excluded.source_url,
    raw_text = excluded.raw_text,
    updated_at = now();
""".strip().format(
                    id=sql_value(row_id),
                    market_id=sql_value(market.get("market_id")),
                    observation_date=sql_value(observation.get("date")),
                    source_type=sql_value("ncei_ghcnd"),
                    station_id=sql_value(station.get("id")),
                    station_name=sql_value(station.get("name")),
                    tmax_f=sql_value(observation.get("tmax_f")),
                    source_url=sql_value("https://www.ncei.noaa.gov/cdo-web/webservices/v2"),
                    raw_text=sql_json(observation),
                )
            )
            emit("")


def emit_scored_seed(emit, scored_markets: dict[str, Any]) -> None:
    emit("-- scored market snapshots")
    for market in scored_markets.get("markets", []):
        row_id = str(deterministic_uuid("scored_snapshot", market["ticker"], market.get("pulled_at")))
        state_hash = hash_json(
            {
                "adjusted_forecast_max_f": market.get("adjusted_forecast_max_f"),
                "forecast_sigma_f": market.get("forecast_sigma_f"),
                "model_probability": market.get("model_probability"),
                "edge": market.get("edge"),
                "signal_short": market.get("signal_short"),
                "market_context": market.get("market_context"),
                "model_signal": market.get("model_signal"),
            }
        )
        emit(
            """
insert into app.scored_market_snapshots (
  id, pulled_at, ticker, event_ticker, market_id, forecast_date, matched_location, matched_latitude,
  matched_longitude, forecast_max_f, forecast_min_f, adjusted_forecast_max_f, forecast_sigma_f,
  noaa_forecast_max_f, open_meteo_forecast_max_f, forecast_source_spread_f, lead_bucket,
  model_probability, edge, signal_short, market_context, model_signal, weather_market_id, state_hash
)
values (
  {id}, {pulled_at}, {ticker}, {event_ticker}, {market_id}, {forecast_date}, {matched_location}, {matched_latitude},
  {matched_longitude}, {forecast_max_f}, {forecast_min_f}, {adjusted_forecast_max_f}, {forecast_sigma_f},
  {noaa_forecast_max_f}, {open_meteo_forecast_max_f}, {forecast_source_spread_f}, {lead_bucket},
  {model_probability}, {edge}, {signal_short}, {market_context}, {model_signal}, {weather_market_id}, {state_hash}
)
on conflict (ticker, pulled_at) do update
set event_ticker = excluded.event_ticker,
    market_id = excluded.market_id,
    forecast_date = excluded.forecast_date,
    matched_location = excluded.matched_location,
    matched_latitude = excluded.matched_latitude,
    matched_longitude = excluded.matched_longitude,
    forecast_max_f = excluded.forecast_max_f,
    forecast_min_f = excluded.forecast_min_f,
    adjusted_forecast_max_f = excluded.adjusted_forecast_max_f,
    forecast_sigma_f = excluded.forecast_sigma_f,
    noaa_forecast_max_f = excluded.noaa_forecast_max_f,
    open_meteo_forecast_max_f = excluded.open_meteo_forecast_max_f,
    forecast_source_spread_f = excluded.forecast_source_spread_f,
    lead_bucket = excluded.lead_bucket,
    model_probability = excluded.model_probability,
    edge = excluded.edge,
    signal_short = excluded.signal_short,
    market_context = excluded.market_context,
    model_signal = excluded.model_signal,
    weather_market_id = excluded.weather_market_id,
    state_hash = excluded.state_hash,
    inserted_at = now();
""".strip().format(
                id=sql_value(row_id),
                pulled_at=sql_value(market.get("pulled_at")),
                ticker=sql_value(market["ticker"]),
                event_ticker=sql_value(market.get("event_ticker")),
                market_id=sql_value(market.get("weather_market_id")),
                forecast_date=sql_value(market.get("forecast_date")),
                matched_location=sql_value(market.get("matched_location")),
                matched_latitude=sql_value(market.get("matched_latitude")),
                matched_longitude=sql_value(market.get("matched_longitude")),
                forecast_max_f=sql_value(market.get("forecast_max_f")),
                forecast_min_f=sql_value(market.get("forecast_min_f")),
                adjusted_forecast_max_f=sql_value(market.get("adjusted_forecast_max_f")),
                forecast_sigma_f=sql_value(market.get("forecast_sigma_f")),
                noaa_forecast_max_f=sql_value(market.get("noaa_forecast_max_f")),
                open_meteo_forecast_max_f=sql_value(market.get("open_meteo_forecast_max_f")),
                forecast_source_spread_f=sql_value(market.get("forecast_source_spread_f")),
                lead_bucket=sql_value(market.get("lead_bucket")),
                model_probability=sql_value(market.get("model_probability")),
                edge=sql_value(market.get("edge")),
                signal_short=sql_value(market.get("signal_short")),
                market_context=sql_value(market.get("market_context")),
                model_signal=sql_value(market.get("model_signal")),
                weather_market_id=sql_value(market.get("weather_market_id")),
                state_hash=sql_value(state_hash),
            )
        )
        emit("")


def emit_daily_bets_seed(emit, bet_payloads: dict[str, dict[str, Any]]) -> None:
    emit("-- daily bet runs and bets")
    for target_date, payload in sorted(bet_payloads.items()):
        bets = payload.get("bets", [])
        generated_at = payload.get("generated_at") or payload.get("resolved_at") or payload.get("logged_at")
        emit(
            """
insert into app.daily_bet_runs (
  target_date, generated_at, starting_bankroll, risk_pct_per_city, stake_per_city_dollars, bet_count
)
values (
  {target_date}, {generated_at}, {starting_bankroll}, {risk_pct_per_city}, {stake_per_city_dollars}, {bet_count}
)
on conflict (target_date) do update
set generated_at = excluded.generated_at,
    starting_bankroll = excluded.starting_bankroll,
    risk_pct_per_city = excluded.risk_pct_per_city,
    stake_per_city_dollars = excluded.stake_per_city_dollars,
    bet_count = excluded.bet_count;
""".strip().format(
                target_date=sql_value(target_date),
                generated_at=sql_value(generated_at),
                starting_bankroll=sql_value(payload.get("starting_bankroll")),
                risk_pct_per_city=sql_value(payload.get("risk_pct_per_city")),
                stake_per_city_dollars=sql_value(payload.get("stake_per_city_dollars")),
                bet_count=sql_value(payload.get("bet_count", len(bets))),
            )
        )
        emit("")

        for bet in bets:
            row_id = str(deterministic_uuid("daily_bet", target_date, bet["city"]))
            emit(
                """
insert into app.daily_bets (
  id, target_date, logged_at, weather_market_id, city, series_ticker, event_ticker, ticker, title,
  strike_type, floor_strike, cap_strike, forecast_date, lead_bucket, forecast_max_f,
  adjusted_forecast_max_f, forecast_sigma_f, recommended_side, model_win_probability, yes_probability,
  kalshi_yes_probability, contract_cost, expected_value, expected_return, bankroll_at_bet,
  risk_pct_of_bankroll, stake_dollars, contract_count, max_profit_dollars, expected_value_dollars,
  yes_ask_dollars, no_ask_dollars, volume, close_time, signal, status, resolved_at, observed_high_f,
  contract_yes_outcome, bet_won, pnl_per_contract, pnl_dollars
)
values (
  {id}, {target_date}, {logged_at}, {weather_market_id}, {city}, {series_ticker}, {event_ticker}, {ticker}, {title},
  {strike_type}, {floor_strike}, {cap_strike}, {forecast_date}, {lead_bucket}, {forecast_max_f},
  {adjusted_forecast_max_f}, {forecast_sigma_f}, {recommended_side}, {model_win_probability}, {yes_probability},
  {kalshi_yes_probability}, {contract_cost}, {expected_value}, {expected_return}, {bankroll_at_bet},
  {risk_pct_of_bankroll}, {stake_dollars}, {contract_count}, {max_profit_dollars}, {expected_value_dollars},
  {yes_ask_dollars}, {no_ask_dollars}, {volume}, {close_time}, {signal}, {status}, {resolved_at}, {observed_high_f},
  {contract_yes_outcome}, {bet_won}, {pnl_per_contract}, {pnl_dollars}
)
on conflict (target_date, city) do update
set logged_at = excluded.logged_at,
    weather_market_id = excluded.weather_market_id,
    series_ticker = excluded.series_ticker,
    event_ticker = excluded.event_ticker,
    ticker = excluded.ticker,
    title = excluded.title,
    strike_type = excluded.strike_type,
    floor_strike = excluded.floor_strike,
    cap_strike = excluded.cap_strike,
    forecast_date = excluded.forecast_date,
    lead_bucket = excluded.lead_bucket,
    forecast_max_f = excluded.forecast_max_f,
    adjusted_forecast_max_f = excluded.adjusted_forecast_max_f,
    forecast_sigma_f = excluded.forecast_sigma_f,
    recommended_side = excluded.recommended_side,
    model_win_probability = excluded.model_win_probability,
    yes_probability = excluded.yes_probability,
    kalshi_yes_probability = excluded.kalshi_yes_probability,
    contract_cost = excluded.contract_cost,
    expected_value = excluded.expected_value,
    expected_return = excluded.expected_return,
    bankroll_at_bet = excluded.bankroll_at_bet,
    risk_pct_of_bankroll = excluded.risk_pct_of_bankroll,
    stake_dollars = excluded.stake_dollars,
    contract_count = excluded.contract_count,
    max_profit_dollars = excluded.max_profit_dollars,
    expected_value_dollars = excluded.expected_value_dollars,
    yes_ask_dollars = excluded.yes_ask_dollars,
    no_ask_dollars = excluded.no_ask_dollars,
    volume = excluded.volume,
    close_time = excluded.close_time,
    signal = excluded.signal,
    status = excluded.status,
    resolved_at = excluded.resolved_at,
    observed_high_f = excluded.observed_high_f,
    contract_yes_outcome = excluded.contract_yes_outcome,
    bet_won = excluded.bet_won,
    pnl_per_contract = excluded.pnl_per_contract,
    pnl_dollars = excluded.pnl_dollars,
    inserted_at = now();
""".strip().format(
                    id=sql_value(row_id),
                    target_date=sql_value(target_date),
                    logged_at=sql_value(bet.get("logged_at")),
                    weather_market_id=sql_value(bet.get("weather_market_id")),
                    city=sql_value(bet.get("city")),
                    series_ticker=sql_value(bet.get("series_ticker")),
                    event_ticker=sql_value(bet.get("event_ticker")),
                    ticker=sql_value(bet.get("ticker")),
                    title=sql_value(bet.get("title")),
                    strike_type=sql_value(bet.get("strike_type")),
                    floor_strike=sql_value(bet.get("floor_strike")),
                    cap_strike=sql_value(bet.get("cap_strike")),
                    forecast_date=sql_value(bet.get("forecast_date")),
                    lead_bucket=sql_value(bet.get("lead_bucket")),
                    forecast_max_f=sql_value(bet.get("forecast_max_f")),
                    adjusted_forecast_max_f=sql_value(bet.get("adjusted_forecast_max_f")),
                    forecast_sigma_f=sql_value(bet.get("forecast_sigma_f")),
                    recommended_side=sql_value(bet.get("recommended_side")),
                    model_win_probability=sql_value(bet.get("model_win_probability")),
                    yes_probability=sql_value(bet.get("yes_probability")),
                    kalshi_yes_probability=sql_value(bet.get("kalshi_yes_probability")),
                    contract_cost=sql_value(bet.get("contract_cost")),
                    expected_value=sql_value(bet.get("expected_value")),
                    expected_return=sql_value(bet.get("expected_return")),
                    bankroll_at_bet=sql_value(bet.get("bankroll_at_bet")),
                    risk_pct_of_bankroll=sql_value(bet.get("risk_pct_of_bankroll")),
                    stake_dollars=sql_value(bet.get("stake_dollars")),
                    contract_count=sql_value(bet.get("contract_count")),
                    max_profit_dollars=sql_value(bet.get("max_profit_dollars")),
                    expected_value_dollars=sql_value(bet.get("expected_value_dollars")),
                    yes_ask_dollars=sql_value(bet.get("yes_ask_dollars")),
                    no_ask_dollars=sql_value(bet.get("no_ask_dollars")),
                    volume=sql_value(bet.get("volume")),
                    close_time=sql_value(bet.get("close_time")),
                    signal=sql_value(bet.get("signal")),
                    status=sql_value(bet.get("status")),
                    resolved_at=sql_value(bet.get("resolved_at")),
                    observed_high_f=sql_value(bet.get("observed_high_f")),
                    contract_yes_outcome=sql_value(as_contract_yes_outcome(bet)),
                    bet_won=sql_value(bet.get("bet_won")),
                    pnl_per_contract=sql_value(bet.get("pnl_per_contract")),
                    pnl_dollars=sql_value(bet.get("pnl_dollars")),
                )
            )
            emit("")


def emit_bankroll_seed(emit, bankroll_history: dict[str, Any]) -> None:
    emit("-- bankroll history")
    for day in bankroll_history.get("days", []):
        target_date = day["date"]
        bankroll_start = day.get("bankroll_start")
        bankroll_end = day.get("bankroll_end")
        total_staked = day.get("total_staked_dollars")
        resolved_bets = day.get("resolved_bet_count", 0)
        bet_count = day.get("bet_count", 0)
        emit(
            """
insert into app.bankroll_history (
  target_date, bankroll_start, bankroll_end, risk_pct_per_city, stake_per_city_dollars, bet_count,
  resolved_bet_count, pending_bet_count, wins, losses, total_staked_dollars, realized_pnl_dollars,
  roi_on_staked, generated_at
)
values (
  {target_date}, {bankroll_start}, {bankroll_end}, {risk_pct_per_city}, {stake_per_city_dollars}, {bet_count},
  {resolved_bet_count}, {pending_bet_count}, {wins}, {losses}, {total_staked_dollars}, {realized_pnl_dollars},
  {roi_on_staked}, {generated_at}
)
on conflict (target_date) do update
set bankroll_start = excluded.bankroll_start,
    bankroll_end = excluded.bankroll_end,
    risk_pct_per_city = excluded.risk_pct_per_city,
    stake_per_city_dollars = excluded.stake_per_city_dollars,
    bet_count = excluded.bet_count,
    resolved_bet_count = excluded.resolved_bet_count,
    pending_bet_count = excluded.pending_bet_count,
    wins = excluded.wins,
    losses = excluded.losses,
    total_staked_dollars = excluded.total_staked_dollars,
    realized_pnl_dollars = excluded.realized_pnl_dollars,
    roi_on_staked = excluded.roi_on_staked,
    generated_at = excluded.generated_at;
""".strip().format(
                target_date=sql_value(target_date),
                bankroll_start=sql_value(bankroll_start),
                bankroll_end=sql_value(bankroll_end),
                risk_pct_per_city=sql_value(day.get("risk_pct_per_city")),
                stake_per_city_dollars=sql_value(day.get("stake_per_city_dollars")),
                bet_count=sql_value(bet_count),
                resolved_bet_count=sql_value(resolved_bets),
                pending_bet_count=sql_value(day.get("pending_bet_count", max(bet_count - resolved_bets, 0))),
                wins=sql_value(day.get("wins", 0)),
                losses=sql_value(day.get("losses", 0)),
                total_staked_dollars=sql_value(total_staked),
                realized_pnl_dollars=sql_value(day.get("realized_pnl_dollars")),
                roi_on_staked=sql_value(day.get("roi_on_staked")),
                generated_at=sql_value(bankroll_history.get("generated_at")),
            )
        )
        emit("")


def load_bet_payloads() -> dict[str, dict[str, Any]]:
    payloads: dict[str, dict[str, Any]] = {}
    snapshot_dir = OUTPUT_DIR / "bets" / "snapshots"
    resolved_dir = OUTPUT_DIR / "bets" / "resolved"

    for path in sorted(snapshot_dir.glob("*.json")):
        payload = load_json(path)
        target_date = payload.get("target_date") or path.stem
        payloads[target_date] = payload

    for path in sorted(resolved_dir.glob("*.json")):
        payload = load_json(path)
        target_date = payload.get("target_date") or path.stem
        payloads[target_date] = payload

    latest_path = OUTPUT_DIR / "bets" / "latest_daily_bets.json"
    if latest_path.exists():
        payload = load_json(latest_path)
        target_date = payload.get("target_date")
        if target_date:
            payloads[target_date] = payload

    return payloads


def as_contract_yes_outcome(bet: dict[str, Any]) -> bool | None:
    bet_won = bet.get("bet_won")
    side = bet.get("recommended_side")
    if bet_won is None or side not in {"yes", "no"}:
        return None
    return bool(bet_won) if side == "yes" else not bool(bet_won)


def parse_event_date(event_ticker: str, title: str | None, close_time: str | None) -> str | None:
    match = re.search(r"-(\d{2})([A-Z]{3})(\d{2})$", event_ticker)
    if match:
        year = 2000 + int(match.group(1))
        month = {
            "JAN": 1,
            "FEB": 2,
            "MAR": 3,
            "APR": 4,
            "MAY": 5,
            "JUN": 6,
            "JUL": 7,
            "AUG": 8,
            "SEP": 9,
            "OCT": 10,
            "NOV": 11,
            "DEC": 12,
        }[match.group(2)]
        day = int(match.group(3))
        return dt.date(year, month, day).isoformat()

    if title:
        title_match = re.search(r"on ([A-Z][a-z]{2} \d{1,2}, \d{4})", title)
        if title_match:
            return dt.datetime.strptime(title_match.group(1), "%b %d, %Y").date().isoformat()

    if close_time:
        return close_time[:10]

    return None


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def deterministic_uuid(*parts: Any) -> uuid.UUID:
    key = "::".join("" if part is None else str(part) for part in parts)
    return uuid.uuid5(UUID_NAMESPACE, key)


def hash_json(value: Any) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def sql_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, (dt.date, dt.datetime)):
        return "'" + value.isoformat().replace("'", "''") + "'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def sql_json(value: Any) -> str:
    return f"{sql_value(json.dumps(value, sort_keys=True))}::jsonb"


def sql_array(values: Iterable[Any]) -> str:
    items = list(values)
    if not items:
        return "array[]::text[]"
    rendered = ", ".join(sql_value(item) for item in items)
    return f"array[{rendered}]"


if __name__ == "__main__":
    raise SystemExit(main())
